export const NOTE_TARGET_LINE_PERCENT = 78;
export const NOTE_HIT_WINDOW_MS = 200;
export const NOTE_PITCH_TOLERANCE_CENTS = 45;

export const SHEET_CURSOR_WIDTH_PX = 4;
export const SHEET_CURSOR_MIN_HEIGHT_PX = 96;
